import argparse
import os
from pathlib import Path


# Generate a compact Co-DETR config specialized for the homework dataset.


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create an MMDetection 3.x CO-DETR R50 config for the SVHN homework dataset."
    )
    parser.add_argument(
        "--base-config",
        type=str,
        default="./external/mmdetection/projects/CO-DETR/configs/codino/co_dino_5scale_r50_8xb2_1x_coco.py",
        help="Path to base CO-DETR config from mmdetection/projects/CO-DETR.",
    )
    parser.add_argument("--data-dir", type=str, default="./nycu-hw2-data", help="Dataset root folder.")
    parser.add_argument(
        "--output",
        type=str,
        default="./configs/codetr/co_dino_5scale_r50_svhn.py",
        help="Path of generated config file.",
    )
    parser.add_argument("--max-epochs", type=int, default=10, help="Training max epochs.")
    parser.add_argument("--batch-size", type=int, default=4, help="Per-process batch size.")
    parser.add_argument(
        "--accumulative-counts",
        type=int,
        default=4,
        help="Gradient accumulation steps (MMEngine accumulative_counts).",
    )
    parser.add_argument(
        "--num-query",
        type=int,
        default=900,
        help="Number of Co-DINO queries. Lower value reduces GPU memory usage.",
    )
    parser.add_argument(
        "--num-dn-queries",
        type=int,
        default=100,
        help="Number of denoising queries. Lower value reduces GPU memory usage.",
    )
    parser.add_argument(
        "--num-co-heads",
        type=int,
        default=3,
        help="Number of co-training heads. Lower value reduces GPU memory usage.",
    )
    parser.add_argument(
        "--work-dir",
        type=str,
        default="./work_dirs/co_detr_r50_svhn",
        help="work_dir path written into generated config.",
    )
    parser.add_argument(
        "--load-from",
        type=str,
        default=None,
        help="Optional full-model checkpoint path/URL written into generated config. Leave unset to keep only backbone pretraining.",
    )
    parser.add_argument(
        "--image-size",
        type=int,
        default=512,
        help="Square image size used to override 1024-based train-time config settings.",
    )
    parser.add_argument(
        "--save-best",
        type=str,
        default="coco/bbox_mAP",
        help="Validation metric name used by MMEngine CheckpointHook save_best.",
    )
    parser.add_argument(
        "--max-keep-ckpts",
        type=int,
        default=3,
        help="How many recent checkpoints to keep. Set to -1 to keep all.",
    )
    return parser.parse_args()


def build_config_text(
    base_config: Path,
    data_dir: Path,
    max_epochs: int,
    batch_size: int,
    accumulative_counts: int,
    num_query: int,
    num_dn_queries: int,
    num_co_heads: int,
    image_size: int,
    work_dir: str,
    load_from: str | None,
    save_best: str,
    max_keep_ckpts: int,
) -> str:
    # The generated file is a normal MMEngine config. It imports the official
    # Co-DETR base config, then patches only dataset paths, class count, image
    # size, training length, and memory-sensitive query settings.
    data_dir_posix = data_dir.as_posix()
    base_config_posix = base_config.as_posix()

    return f"""# Auto-generated by create_codetr_svhn_config.py
# Target stack: MMDetection 3.x + projects/CO-DETR

_base_ = r'{base_config_posix}'

metainfo = dict(classes=tuple(str(i) for i in range(10)))
num_classes = 10
image_size = ({image_size}, {image_size})

data_root = r'{data_dir_posix}'
train_ann_file = 'codetr_coco/annotations/instances_train2017.json'
val_ann_file = 'codetr_coco/annotations/instances_val2017.json'
test_ann_file = 'codetr_coco/annotations/image_info_test-dev2017.json'

train_data_prefix = dict(img='train/')
val_data_prefix = dict(img='valid/')
test_data_prefix = dict(img='test/')


def _patch_dataset_node(node, ann_file, data_prefix):
    if not isinstance(node, dict):
        return
    if 'dataset' in node and isinstance(node['dataset'], dict):
        _patch_dataset_node(node['dataset'], ann_file, data_prefix)
    if 'ann_file' in node or 'data_prefix' in node or node.get('type', '').endswith('CocoDataset'):
        node['metainfo'] = metainfo
        node['data_root'] = data_root
        node['ann_file'] = ann_file
        node['data_prefix'] = data_prefix


def _patch_dataloader(loader, ann_file, data_prefix, batch=None):
    if not isinstance(loader, dict):
        return loader
    loader = dict(loader)
    if batch is not None:
        loader['batch_size'] = int(batch)
    if 'dataset' in loader:
        _patch_dataset_node(loader['dataset'], ann_file, data_prefix)
    return loader


train_dataloader = _patch_dataloader(_base_.train_dataloader, train_ann_file, train_data_prefix, batch={batch_size})
val_dataloader = _patch_dataloader(_base_.val_dataloader, val_ann_file, val_data_prefix)
test_dataloader = _patch_dataloader(_base_.test_dataloader, test_ann_file, test_data_prefix)

val_evaluator = dict(_base_.val_evaluator)
val_evaluator['ann_file'] = data_root + '/' + val_ann_file

test_evaluator = dict(_base_.test_evaluator)
test_evaluator['ann_file'] = data_root + '/' + test_ann_file


def _set_num_classes(node, value):
    if isinstance(node, dict):
        for key, val in node.items():
            if key == 'num_classes':
                node[key] = value
            else:
                _set_num_classes(val, value)
    elif isinstance(node, list):
        for item in node:
            _set_num_classes(item, value)


def _patch_image_size(node):
    if isinstance(node, dict):
        node_type = node.get('type')
        if node_type in ('Resize', 'RandomResize'):
            node['scale'] = image_size
            node['keep_ratio'] = False
        elif node_type == 'RandomChoiceResize':
            scales = node.get('scales')
            if isinstance(scales, list) and scales:
                node['scales'] = [image_size for _ in scales]
            node['keep_ratio'] = False
        elif node_type == 'RandomCrop':
            node['crop_size'] = image_size
        elif node_type in ('Pad', 'BatchFixedSizePad'):
            node['size'] = image_size

        for val in node.values():
            _patch_image_size(val)
    elif isinstance(node, list):
        for item in node:
            _patch_image_size(item)


_patch_image_size(train_dataloader)
_patch_image_size(val_dataloader)
_patch_image_size(test_dataloader)


model = dict(_base_.model)
_set_num_classes(model, num_classes)
_patch_image_size(model)

# Memory-friendly defaults for 10-12GB GPUs.
if isinstance(model, dict):
    query_head = model.get('query_head', None)
    if query_head is not None:
        query_head = dict(query_head)
        query_head['num_query'] = {num_query}
        dn_cfg = dict(query_head.get('dn_cfg', {{}}))
        group_cfg = dict(dn_cfg.get('group_cfg', {{}}))
        group_cfg['num_dn_queries'] = {num_dn_queries}
        dn_cfg['group_cfg'] = group_cfg
        query_head['dn_cfg'] = dn_cfg
        transformer = dict(query_head.get('transformer', {{}}))
        transformer['num_co_heads'] = {num_co_heads}
        query_head['transformer'] = transformer
        model['query_head'] = query_head

if hasattr(_base_, 'batch_augments'):
    batch_augments = [dict(item) if isinstance(item, dict) else item for item in _base_.batch_augments]
    _patch_image_size(batch_augments)

if hasattr(_base_, 'load_pipeline'):
    load_pipeline = [dict(item) if isinstance(item, dict) else item for item in _base_.load_pipeline]
    _patch_image_size(load_pipeline)

if hasattr(_base_, 'train_pipeline'):
    train_pipeline = [dict(item) if isinstance(item, dict) else item for item in _base_.train_pipeline]
    _patch_image_size(train_pipeline)

if hasattr(_base_, 'test_pipeline'):
    test_pipeline = [dict(item) if isinstance(item, dict) else item for item in _base_.test_pipeline]
    _patch_image_size(test_pipeline)

if hasattr(_base_, 'max_epochs'):
    max_epochs = {max_epochs}

train_cfg = _base_.train_cfg
if isinstance(train_cfg, dict):
    train_cfg = dict(train_cfg)
    train_cfg['max_epochs'] = {max_epochs}
elif isinstance(train_cfg, list):
    train_cfg = [dict(item) if isinstance(item, dict) else item for item in train_cfg]
    for item in train_cfg:
        if isinstance(item, dict):
            item['max_epochs'] = {max_epochs}

# Keep standard precision wrapper + gradient accumulation.
optim_wrapper = dict(_base_.optim_wrapper)
optim_wrapper['type'] = 'OptimWrapper'
optim_wrapper.pop('loss_scale', None)
optim_wrapper['accumulative_counts'] = {accumulative_counts}

default_hooks = dict(getattr(_base_, 'default_hooks', {{}}))
checkpoint_hook = dict(default_hooks.get('checkpoint', {{}}))
checkpoint_hook['interval'] = 1
checkpoint_hook['save_best'] = r'{save_best}'
checkpoint_hook['rule'] = 'greater'
checkpoint_hook['save_last'] = True
if {max_keep_ckpts} >= 0:
    checkpoint_hook['max_keep_ckpts'] = {max_keep_ckpts}
else:
    checkpoint_hook.pop('max_keep_ckpts', None)
default_hooks['checkpoint'] = checkpoint_hook

work_dir = r'{work_dir}'
load_from = {repr(load_from)}
"""


def main() -> None:
    args = parse_args()

    if args.max_epochs <= 0:
        raise ValueError("--max-epochs must be positive.")
    if args.batch_size <= 0:
        raise ValueError("--batch-size must be positive.")
    if args.accumulative_counts <= 0:
        raise ValueError("--accumulative-counts must be positive.")
    if args.num_query <= 0:
        raise ValueError("--num-query must be positive.")
    if args.num_dn_queries <= 0:
        raise ValueError("--num-dn-queries must be positive.")
    if args.num_co_heads <= 0:
        raise ValueError("--num-co-heads must be positive.")
    if args.image_size <= 0:
        raise ValueError("--image-size must be positive.")
    if args.max_keep_ckpts == 0 or args.max_keep_ckpts < -1:
        raise ValueError("--max-keep-ckpts must be -1 or a positive integer.")

    base_config = Path(args.base_config)
    if not base_config.exists():
        raise FileNotFoundError(f"Base config not found: {base_config}")

    data_dir = Path(args.data_dir).resolve()
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # MMEngine resolves _base_ relative to the current config file directory.
    # Use relative paths from output config folder for portability across machines.
    output_dir = output_path.parent.resolve()
    base_config_rel = Path(os.path.relpath(base_config.resolve(), output_dir))
    data_dir_abs = data_dir.resolve()

    generated = build_config_text(
        base_config=base_config_rel,
        data_dir=data_dir_abs,
        max_epochs=args.max_epochs,
        batch_size=args.batch_size,
        accumulative_counts=args.accumulative_counts,
        num_query=args.num_query,
        num_dn_queries=args.num_dn_queries,
        num_co_heads=args.num_co_heads,
        image_size=args.image_size,
        work_dir=args.work_dir,
        load_from=args.load_from,
        save_best=args.save_best,
        max_keep_ckpts=args.max_keep_ckpts,
    )

    output_path.write_text(generated, encoding="utf-8")
    print("Generated config:")
    print(output_path)


if __name__ == "__main__":
    main()
